package br.com.samg.mmouse.gui;

import br.com.samg.mmouse.gui.constants.OptionsToExistDialogConstants;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

/**
 * painel principal da aplicação
 */
public class Application extends javax.swing.JFrame {
    
    /**
     * Painel de opções para sair da aplicação.
     */
    OptionsToExistDialog optionsToExistDialog;
    
    /**
     * Inicializa e configura os componentes.
     */
    public Application() {
        initComponents();
        configureComponents();
    }

    /**
     * Configura os componets.
     */
    private void configureComponents() {
        try {
            textIPMaquina.setText(InetAddress.getLocalHost().getHostAddress());
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível obter o IP da máquina", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int positionX = (int) (screenSize.getWidth() - getWidth()) / 2;
        int positionY = (int) (screenSize.getHeight() - getHeight()) / 2;

        this.setLocation(positionX, positionY);
        
        this.optionsToExistDialog = new OptionsToExistDialog();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        principalPanel = new javax.swing.JPanel();
        textIPMaquina = new javax.swing.JTextField();
        labelIPMaquina = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        buttonEncerrar = new javax.swing.JButton();
        buttonIniciar = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        footerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MMouse");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        principalPanel.setPreferredSize(new java.awt.Dimension(400, 190));
        principalPanel.setLayout(new java.awt.GridBagLayout());

        textIPMaquina.setEditable(false);
        textIPMaquina.setFocusable(false);
        textIPMaquina.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        principalPanel.add(textIPMaquina, gridBagConstraints);

        labelIPMaquina.setText("Digite o seguinte IP no Aplicativo depois de iniciar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        principalPanel.add(labelIPMaquina, gridBagConstraints);

        panelButtons.setLayout(new java.awt.GridBagLayout());

        buttonEncerrar.setText("Encerrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        panelButtons.add(buttonEncerrar, gridBagConstraints);

        buttonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 4);
        panelButtons.add(buttonIniciar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        principalPanel.add(panelButtons, gridBagConstraints);

        getContentPane().add(principalPanel, java.awt.BorderLayout.CENTER);

        footerLabel.setText("É necessário que ambos dispositivos estejam na mesma rede.");
        footerPanel.add(footerLabel);

        getContentPane().add(footerPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Processamento a ser feito ao fechar a janela, solicitando a opções para
     * sair.
     * 
     * @param evt Eventos de janelas.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.optionsToExistDialog.setLocationRelativeTo(this);
        this.optionsToExistDialog.setModal(true);
        this.optionsToExistDialog.setVisible(true);

        if (optionsToExistDialog.getSelectOptionToExit()
                == OptionsToExistDialogConstants.BACKGROUND_OPTION) {
            this.setDefaultCloseOperation(
                    javax.swing.WindowConstants.HIDE_ON_CLOSE);
        } else if (optionsToExistDialog.getSelectOptionToExit()
                == OptionsToExistDialogConstants.CLOSE_OPTION) {
            this.setDefaultCloseOperation(
                    javax.swing.WindowConstants.EXIT_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(
                    javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEncerrar;
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel labelIPMaquina;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JTextField textIPMaquina;
    // End of variables declaration//GEN-END:variables
}
