package br.com.samg.mmouse.gui;

import br.com.samg.mmouse.gui.constants.OptionsToExistDialogConstants;

/**
 * Painel de opções para sair da aplicação.
 */
public class OptionsToExistDialog extends javax.swing.JDialog {

    private int selectOptionToExit;

    /**
     * Inicializa e configura os componentes.
     */
    public OptionsToExistDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        panelRadioButtons = new javax.swing.JPanel();
        radioButtonFecharPrograma = new javax.swing.JRadioButton();
        radioButtonSegundoPlano = new javax.swing.JRadioButton();
        footerPanelButtons = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        setTitle("Sair");
        setMaximumSize(new java.awt.Dimension(220, 150));
        setMinimumSize(new java.awt.Dimension(220, 150));
        setPreferredSize(new java.awt.Dimension(220, 150));

        panelRadioButtons.setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(radioButtonFecharPrograma);
        radioButtonFecharPrograma.setText("Fechar Programa");
        radioButtonFecharPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelRadioButtons.add(radioButtonFecharPrograma, gridBagConstraints);

        buttonGroup.add(radioButtonSegundoPlano);
        radioButtonSegundoPlano.setSelected(true);
        radioButtonSegundoPlano.setText("Manter em Segundo Plano");
        radioButtonSegundoPlano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelRadioButtons.add(radioButtonSegundoPlano, gridBagConstraints);

        getContentPane().add(panelRadioButtons, java.awt.BorderLayout.CENTER);

        footerPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonOk.setText("Ok");
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });
        footerPanelButtons.add(buttonOk);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseClicked(evt);
            }
        });
        footerPanelButtons.add(buttonCancelar);

        getContentPane().add(footerPanelButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Processamento a ser feito caso seja clicado no botão ok.
     * 
     * @param evt Eventos do Mousse.
     */
    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked

        if (radioButtonSegundoPlano.isSelected()) {
            setSelectOptionToExit(
                    OptionsToExistDialogConstants.BACKGROUND_OPTION);
        } else {
            setSelectOptionToExit(OptionsToExistDialogConstants.CLOSE_OPTION);
        }

        this.setVisible(false);
    }//GEN-LAST:event_buttonOkMouseClicked

    /**
     * Processamento a ser feito caso seja clicado no botão cancelar.
     * 
     * @param evt Eventos do Mouse.
     */
    private void buttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseClicked
        //Preciso apenas esconder o componente.
        this.setVisible(false);
    }//GEN-LAST:event_buttonCancelarMouseClicked

    /**
     * Retorna a opção selecionada para sair.
     * 
     * @return A opção selecionada para sair.
     */
    public int getSelectOptionToExit() {
        return selectOptionToExit;
    }
    
    /**
     * Define a opção desejada ao sair.
     * 
     * @param selectOptionToExit A opção desejada ao sair.
     */
    public void setSelectOptionToExit(int selectOptionToExit) {
        this.selectOptionToExit = selectOptionToExit;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPanel footerPanelButtons;
    private javax.swing.JPanel panelRadioButtons;
    private javax.swing.JRadioButton radioButtonFecharPrograma;
    private javax.swing.JRadioButton radioButtonSegundoPlano;
    // End of variables declaration//GEN-END:variables

}
